version: '2.23'
services:

  solr1:
    image: solr:9.4
    container_name: solr1
    ports:
     - "8982:8983"
    environment:
      - ZK_HOST=zoo1:2181,zoo2:2181,zoo3:2181
    networks:
      - solr
networks:
  solr: